// Employee CRUD
export const EMPLOYEE_CREATE_REQUEST = "EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS = "EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL    = "EMPLOYEE_CREATE_FAIL";

export const EMPLOYEE_READ_REQUEST   = "EMPLOYEE_READ_REQUEST";
export const EMPLOYEE_READ_SUCCESS   = "EMPLOYEE_READ_SUCCESS";
export const EMPLOYEE_READ_FAIL      = "EMPLOYEE_READ_FAIL";

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAIL    = "EMPLOYEE_UPDATE_FAIL";

export const EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAIL    = "EMPLOYEE_DELETE_FAIL";

// Dropdowns
export const DEPARTMENT_LIST_REQUEST = "DEPARTMENT_LIST_REQUEST";
export const DEPARTMENT_LIST_SUCCESS = "DEPARTMENT_LIST_SUCCESS";
export const DEPARTMENT_LIST_FAIL    = "DEPARTMENT_LIST_FAIL";

export const LOCATION_LIST_REQUEST   = "LOCATION_LIST_REQUEST";
export const LOCATION_LIST_SUCCESS   = "LOCATION_LIST_SUCCESS";
export const LOCATION_LIST_FAIL      = "LOCATION_LIST_FAIL";

export const DESIGNATION_LIST_REQUEST = "DESIGNATION_LIST_REQUEST";
export const DESIGNATION_LIST_SUCCESS = "DESIGNATION_LIST_SUCCESS";
export const DESIGNATION_LIST_FAIL    = "DESIGNATION_LIST_FAIL";

export const EDUCATION_LIST_REQUEST = "EDUCATION_LIST_REQUEST";
export const EDUCATION_LIST_SUCCESS = "EDUCATION_LIST_SUCCESS";
export const EDUCATION_LIST_FAIL    = "EDUCATION_LIST_FAIL";
