export const MEMBER_CREATE_REQUEST = "MEMBER_CREATE_REQUEST";
export const MEMBER_CREATE_SUCCESS = "MEMBER_CREATE_SUCCESS";
export const MEMBER_CREATE_FAIL = "MEMBER_CREATE_FAIL";

export const MEMBER_READ_REQUEST = "MEMBER_READ_REQUEST";
export const MEMBER_READ_SUCCESS = "MEMBER_READ_SUCCESS";
export const MEMBER_READ_FAIL = "MEMBER_READ_FAIL";

export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";
